# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Records a dataset. Actions for the robot can be either generated by teleoperation or by a policy.
    包含vr上的按钮来进行控制录制的开始和结束。
Example:

```shell
lerobot-record \
    --robot.type=tron2 \
    --robot.robot_ip="10.192.1.2" \
    --dataset.repo_id=<my_username>/<my_dataset_name> \
    --dataset.num_episodes=2 \
    --dataset.single_task="Grab the cube" \
    --display_data=true
```
"""

import logging
import time
import gc
from dataclasses import asdict, dataclass, field
from pathlib import Path
from pprint import pformat
from typing import Any

from lerobot.cameras import (  # noqa: F401
    CameraConfig,  # noqa: F401
)
from lerobot.cameras.opencv.configuration_opencv import OpenCVCameraConfig  # noqa: F401
from lerobot.cameras.realsense.configuration_realsense import RealSenseCameraConfig  # noqa: F401
# Register Tron2 and Tac3D configs
from lerobot.tactile.configs import Tac3DSensorConfig  # noqa: F401
from lerobot.robots.tron2.tron2_config import Tron2RobotConfig  # noqa: F401

from lerobot.configs import parser
from lerobot.configs.policies import PreTrainedConfig
from lerobot.datasets.image_writer import safe_stop_image_writer
from lerobot.datasets.lerobot_dataset import LeRobotDataset
from lerobot.datasets.pipeline_features import aggregate_pipeline_dataset_features, create_initial_features
from lerobot.datasets.utils import build_dataset_frame, combine_feature_dicts
from lerobot.datasets.video_utils import VideoEncodingManager
from lerobot.policies.factory import make_policy, make_pre_post_processors
from lerobot.policies.pretrained import PreTrainedPolicy
from lerobot.policies.utils import make_robot_action
from lerobot.processor import (
    PolicyAction,
    PolicyProcessorPipeline,
    RobotAction,
    RobotObservation,
    RobotProcessorPipeline,
    make_default_processors,
)
from lerobot.processor.rename_processor import rename_stats
from lerobot.robots import (  # noqa: F401
    Robot,
    RobotConfig,
    make_robot_from_config,
)
from lerobot.teleoperators import (  # noqa: F401
    Teleoperator,
    TeleoperatorConfig,
    make_teleoperator_from_config,
)
from lerobot.teleoperators.keyboard.teleop_keyboard import KeyboardTeleop
from lerobot.utils.constants import ACTION, OBS_STR
from lerobot.utils.control_utils import (
    init_keyboard_listener,
    is_headless,
    predict_action,
    sanity_check_dataset_name,
    sanity_check_dataset_robot_compatibility,
)
from lerobot.utils.import_utils import register_third_party_plugins
from lerobot.utils.robot_utils import busy_wait
from lerobot.utils.utils import (
    get_safe_torch_device,
    init_logging,
    log_say,
)
from lerobot.utils.visualization_utils import init_rerun, log_rerun_data


@dataclass
class DatasetRecordConfig:
    # Dataset identifier. By convention it should match '{hf_username}/{dataset_name}' (e.g. `lerobot/test`).
    repo_id: str
    # A short but accurate description of the task performed during the recording (e.g. "Pick the Lego block and drop it in the box on the right.")
    single_task: str
    # Root directory where the dataset will be stored (e.g. 'dataset/path').
    root: str | Path | None = None
    # Limit the frames per second.
    fps: int = 30
    # Number of seconds for data recording for each episode.
    episode_time_s: int | float = 99999
    # Number of seconds for resetting the environment after each episode.
    reset_time_s: int | float = 15
    # Number of episodes to record.
    num_episodes: int = 50
    # Encode frames in the dataset into video
    video: bool = True
    # Upload dataset to Hugging Face hub.
    push_to_hub: bool = True
    # Upload on private repository on the Hugging Face hub.
    private: bool = False
    # Add tags to your dataset on the hub.
    tags: list[str] | None = None
    # Number of subprocesses handling the saving of frames as PNG. Set to 0 to use threads only;
    # set to ≥1 to use subprocesses, each using threads to write images. The best number of processes
    # and threads depends on your system. We recommend 4 threads per camera with 0 processes.
    # If fps is unstable, adjust the thread count. If still unstable, try using 1 or more subprocesses.
    num_image_writer_processes: int = 0
    # Number of threads writing the frames as png images on disk, per camera.
    # Too many threads might cause unstable teleoperation fps due to main thread being blocked.
    # Not enough threads might cause low camera fps.
    num_image_writer_threads_per_camera: int = 4
    # Number of episodes to record before batch encoding videos
    # Set to 1 for immediate encoding (default behavior), or higher for batched encoding
    video_encoding_batch_size: int = 1
    # Rename map for the observation to override the image and state keys
    rename_map: dict[str, str] = field(default_factory=dict)

    def __post_init__(self):
        if self.single_task is None:
            raise ValueError("You need to provide a task as argument in `single_task`.")


@dataclass
class RecordConfig:
    robot: RobotConfig
    dataset: DatasetRecordConfig
    # Whether to control the robot with a teleoperator
    teleop: TeleoperatorConfig | None = None
    # Whether to control the robot with a policy
    policy: PreTrainedConfig | None = None
    # Display all cameras on screen
    display_data: bool = False
    # Use vocal synthesis to read events.
    play_sounds: bool = True
    # Resume recording on an existing dataset.
    resume: bool = False

    def __post_init__(self):
        # HACK: We parse again the cli args here to get the pretrained path if there was one.
        policy_path = parser.get_path_arg("policy")
        if policy_path:
            cli_overrides = parser.get_cli_overrides("policy")
            self.policy = PreTrainedConfig.from_pretrained(policy_path, cli_overrides=cli_overrides)
            self.policy.pretrained_path = policy_path

    @classmethod
    def __get_path_fields__(cls) -> list[str]:
        """This enables the parser to load config from the policy using `--policy.path=local/dir`"""
        return ["policy"]


""" --------------- record_loop() data flow --------------------------
       [ Robot ]
           V
     [ robot.get_observation() ] ---> raw_obs
           V
     [ robot_observation_processor ] ---> processed_obs
           V
     .-----( ACTION LOGIC )------------------.
     V                                       V
     [ From Teleoperator ]                   [ From Policy ]
     |                                       |
     |  [teleop.get_action] -> raw_action    |   [predict_action]
     |          |                            |          |
     |          V                            |          V
     | [teleop_action_processor]             |          |
     |          |                            |          |
     '---> processed_teleop_action           '---> processed_policy_action
     |                                       |
     '-------------------------.-------------'
                               V
                  [ robot_action_processor ] --> robot_action_to_send
                               V
                    [ robot.send_action() ] -- (Robot Executes)
                               V
                    ( Save to Dataset )
                               V
                  ( Rerun Log / Loop Wait )
"""


@safe_stop_image_writer
def record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    teleop_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],  # runs after teleop
    robot_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],  # runs before robot
    robot_observation_processor: RobotProcessorPipeline[
        RobotObservation, RobotObservation
    ],  # runs after robot
    dataset: LeRobotDataset | None = None,
    teleop: Teleoperator | list[Teleoperator] | None = None,
    policy: PreTrainedPolicy | None = None,
    preprocessor: PolicyProcessorPipeline[dict[str, Any], dict[str, Any]] | None = None,
    postprocessor: PolicyProcessorPipeline[PolicyAction, PolicyAction] | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
):
    if dataset is not None and dataset.fps != fps:
        raise ValueError(f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps}).")

    teleop_arm = teleop_keyboard = None
    if isinstance(teleop, list):
        teleop_keyboard = next((t for t in teleop if isinstance(t, KeyboardTeleop)), None)
        teleop_arm = next((t for t in teleop if t is not teleop_keyboard), None)

    # Reset policy and processor if they are provided
    if policy is not None and preprocessor is not None and postprocessor is not None:
        policy.reset()
        preprocessor.reset()
        postprocessor.reset()

    # Disable garbage collection during the recording loop to prevent latency spikes
    # GC pause can cause sudden frame drops across all sensors (e.g. at 17s / 500 frames)
    gc.disable()

    try:
        timestamp = 0
        start_episode_t = time.perf_counter()
        logging.info(
            "record_loop start: control_time_s=%s, fps=%s, dataset_present=%s",
            control_time_s,
            fps,
            dataset is not None,
        )
        local_loop_index = 0
        while timestamp < control_time_s:
            
            start_loop_t = time.perf_counter()

            if events["exit_early"]:
                events["exit_early"] = False
                break

            # Get robot observation
            t_obs_start = time.perf_counter()
            obs = robot.get_observation()
            t_obs = time.perf_counter() - t_obs_start

            # Applies a pipeline to the raw robot observation, default is IdentityProcessor
            obs_processed = robot_observation_processor(obs)

            if policy is not None or dataset is not None:
                observation_frame = build_dataset_frame(dataset.features, obs_processed, prefix=OBS_STR)
                t_build_obs = time.perf_counter()

            # Get action from either policy or teleop
            if policy is not None and preprocessor is not None and postprocessor is not None:
                action_values = predict_action(
                    observation=observation_frame,
                    policy=policy,
                    device=get_safe_torch_device(policy.config.device),
                    preprocessor=preprocessor,
                    postprocessor=postprocessor,
                    use_amp=policy.config.use_amp,
                    task=single_task,
                    robot_type=robot.robot_type,
                )

                act_processed_policy: RobotAction = make_robot_action(action_values, dataset.features)

            elif policy is None and isinstance(teleop, Teleoperator):
                act = teleop.get_action()
                act_processed_teleop = teleop_action_processor((act, obs))

            elif policy is None and isinstance(teleop, list):
                if teleop_arm and teleop_keyboard:
                    arm_action = teleop_arm.get_action()
                    arm_action = {f"arm_{k}": v for k, v in arm_action.items()}
                    keyboard_action = teleop_keyboard.get_action()
                    base_action = robot._from_keyboard_to_base_action(keyboard_action)
                    act = {**arm_action, **base_action} if len(base_action) > 0 else arm_action
                else:
                    act = teleop[0].get_action()
                act_processed_teleop = teleop_action_processor((act, obs))
            else:
                logging.info("No policy or teleoperator provided, skipping action generation.")
                continue

            # Applies a pipeline to the action
            if policy is not None and act_processed_policy is not None:
                action_values = act_processed_policy
                robot_action_to_send = robot_action_processor((act_processed_policy, obs))
            else:
                action_values = act_processed_teleop
                robot_action_to_send = robot_action_processor((act_processed_teleop, obs))

            t_action_proc = time.perf_counter()
            # Send action to robot
            t_send_start = time.perf_counter()
            _sent_action = robot.send_action(robot_action_to_send)
            t_send = time.perf_counter() - t_send_start

            # Write to dataset
            t_add_start = None
            t_add = 0.0
            if dataset is not None:
                t_add_start = time.perf_counter()
                action_frame = build_dataset_frame(dataset.features, action_values, prefix=ACTION)
                frame = {**observation_frame, **action_frame, "task": single_task}
                dataset.add_frame(frame)
                t_add = time.perf_counter() - t_add_start

            if display_data:
                log_rerun_data(observation=obs_processed, action=action_values)

            dt_s = time.perf_counter() - start_loop_t
            busy_wait(1 / fps - dt_s)

            timestamp = time.perf_counter() - start_episode_t
            
            if dataset is None:
                loop_index = local_loop_index
            else:
                loop_index = dataset.episode_buffer["size"] if dataset.episode_buffer is not None else 0
            
            if loop_index % max(1, int(fps)) == 0:
                logging.info(
                    "record_loop sample: iter=%s obs_ms=%.3f build_obs_ms=%.3f send_ms=%.3f add_ms=%.3f loop_ms=%.3f",
                    loop_index,
                    t_obs * 1000,
                    (time.perf_counter() - t_build_obs) * 1000 if 't_build_obs' in locals() else 0.0,
                    t_send * 1000 if 't_send' in locals() else 0.0,
                    t_add * 1000,
                    dt_s * 1000,
                )
            
            local_loop_index += 1

        actual_duration = time.perf_counter() - start_episode_t
        try:
            frames_collected = (
                dataset.episode_buffer["size"] if (dataset is not None and dataset.episode_buffer is not None) else 0
            )
        except Exception:
            frames_collected = -1
        logging.info(
            "record_loop end: requested_s=%s actual_s=%.3f frames=%s",
            control_time_s,
            actual_duration,
            frames_collected,
        )

        try:
            if hasattr(robot, "config") and getattr(robot.config, "restore_on_disconnect", False) and hasattr(robot, "restore_initial_pose"):
                logging.info("record_loop: restoring robot to configured initial pose(s)")
                # ... restoration logic ...
                try:
                    if getattr(robot.config, "use_dual", False):
                         for arm_name in ("left_arm", "right_arm"):
                            robot.restore_initial_pose(arm_name)
                    else:
                        robot.restore_initial_pose(robot.config.arm)
                except Exception:
                    pass
        except Exception:
            pass
    finally:
        # Re-enable garbage collection after the episode loop
        gc.enable()
        gc.collect()


@parser.wrap()
def record(cfg: RecordConfig) -> LeRobotDataset:
    init_logging()
    logging.info(pformat(asdict(cfg)))
    if cfg.display_data:
        init_rerun(session_name="recording")

    robot = make_robot_from_config(cfg.robot)
    teleop = make_teleoperator_from_config(cfg.teleop) if cfg.teleop is not None else None

    teleop_action_processor, robot_action_processor, robot_observation_processor = make_default_processors()

    dataset_features = combine_feature_dicts(
        aggregate_pipeline_dataset_features(
            pipeline=teleop_action_processor,
            initial_features=create_initial_features(
                action=robot.action_features
            ),
            use_videos=cfg.dataset.video,
        ),
        aggregate_pipeline_dataset_features(
            pipeline=robot_observation_processor,
            initial_features=create_initial_features(observation=robot.observation_features),
            use_videos=cfg.dataset.video,
        ),
    )

    if cfg.resume:
        dataset = LeRobotDataset(
            cfg.dataset.repo_id,
            root=cfg.dataset.root,
            batch_encoding_size=cfg.dataset.video_encoding_batch_size,
        )

        if hasattr(robot, "cameras") and len(robot.cameras) > 0:
            dataset.start_image_writer(
                num_processes=cfg.dataset.num_image_writer_processes,
                num_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
            )
        sanity_check_dataset_robot_compatibility(dataset, robot, cfg.dataset.fps, dataset_features)
    else:
        sanity_check_dataset_name(cfg.dataset.repo_id, cfg.policy)
        dataset = LeRobotDataset.create(
            cfg.dataset.repo_id,
            cfg.dataset.fps,
            root=cfg.dataset.root,
            robot_type=robot.name,
            features=dataset_features,
            use_videos=cfg.dataset.video,
            image_writer_processes=cfg.dataset.num_image_writer_processes,
            image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
            batch_encoding_size=cfg.dataset.video_encoding_batch_size,
        )

    policy = None if cfg.policy is None else make_policy(cfg.policy, ds_meta=dataset.meta)
    preprocessor = None
    postprocessor = None
    if cfg.policy is not None:
        preprocessor, postprocessor = make_pre_post_processors(
            policy_cfg=cfg.policy,
            pretrained_path=cfg.policy.pretrained_path,
            dataset_stats=rename_stats(dataset.meta.stats, cfg.dataset.rename_map),
            preprocessor_overrides={
                "device_processor": {"device": cfg.policy.device},
                "rename_observations_processor": {"rename_map": cfg.dataset.rename_map},
            },
        )

    robot.connect()
    if teleop is not None:
        teleop.connect()

    warmup_cameras(robot, duration_s=1.5)

    listener, events = init_keyboard_listener()

    with VideoEncodingManager(dataset):
        recorded_episodes = 0
        while recorded_episodes < cfg.dataset.num_episodes and not events["stop_recording"]:
            
            # 等待开始信号
            print(f"\n--- [Episode {dataset.num_episodes + 1}/{cfg.dataset.num_episodes}] ---")
            print("等待按 'S' 开始录制...")
            
            while not events.get("start_episode", False):
                if events.get("stop_recording", False): break
                time.sleep(0.05)
                
            if events.get("stop_recording", False): break
            
            # 清除标志位
            events["start_episode"] = False
            events["exit_early"] = False
            events["discard_episode"] = False

            # 清空缓存
            if dataset.episode_buffer:
                dataset.clear_episode_buffer()

            log_say(f"Recording episode {dataset.num_episodes + 1}", cfg.play_sounds)
            print("录制中... (按 Space 保存，按 L 或 Backspace 丢弃)")
            
            # 开始录制 (依靠键盘的 exit_early 退出)
            try:
                record_loop(
                    robot=robot,
                    events=events,
                    fps=cfg.dataset.fps,
                    teleop_action_processor=teleop_action_processor,
                    robot_action_processor=robot_action_processor,
                    robot_observation_processor=robot_observation_processor,
                    teleop=teleop,
                    policy=policy,
                    preprocessor=preprocessor,
                    postprocessor=postprocessor,
                    dataset=dataset,
                    control_time_s=cfg.dataset.episode_time_s, 
                    single_task=cfg.dataset.single_task,
                    display_data=cfg.display_data,
                )
            except KeyboardInterrupt:
                events["stop_recording"] = True
                break

            if events.get("stop_recording", False):
                break

            # --- 录制结束，确认保存逻辑 ---
            if events.get("discard_episode", False):
                print("\n🗑️ 丢弃当前 episode...")
                logging.warning(f"用户丢弃 episode {dataset.num_episodes + 1}")
                log_say("Discarding Episode", cfg.play_sounds)
                dataset.clear_episode_buffer()
                events["discard_episode"] = False
            elif dataset.episode_buffer and dataset.episode_buffer["size"] > 0:
                print(f"\n💾 保存 episode {dataset.num_episodes + 1}...")
                log_say("Saving Episode", cfg.play_sounds)
                dataset.save_episode()
                recorded_episodes += 1
            else:
                print("\n⚠️ episode_buffer 为空，没有数据可保存")
                
            events["exit_early"] = False # 重置状态
            # --- [修改结束] ---

    log_say("Stop recording", cfg.play_sounds, blocking=True)

    robot.disconnect()
    if teleop is not None:
        teleop.disconnect()

    if not is_headless() and listener is not None:
        listener.stop()

    if cfg.dataset.push_to_hub:
        dataset.push_to_hub(tags=cfg.dataset.tags, private=cfg.dataset.private)

    log_say("Exiting", cfg.play_sounds)
    return dataset


def main():
    register_third_party_plugins()
    record()


def warmup_cameras(robot, duration_s: float = 1.5) -> None:
    """Performs a quick warm-up by reading frames from all robot cameras for duration_s seconds.

    This helps cameras stabilise auto-exposure / white-balance before actual recording.
    """
    cams = getattr(robot, "cameras", None)
    if not cams:
        return

    # Track per-camera successful reads to help debugging
    # If `cams` is a mapping (dict), extract (name, cam) pairs so we can report names
    cam_names = None
    try:
        if hasattr(cams, "items"):
            cam_items = list(cams.items())
            cam_names = [k for k, _ in cam_items]
            cam_list = [v for _, v in cam_items]
        else:
            cam_list = list(cams)
            cam_names = [str(i) for i in range(len(cam_list))]
    except Exception:
        # fallback: try to use cams as iterable
        cam_list = cams
        cam_names = None

    logging.info(f"Warming up {len(cam_list)} camera(s) for {duration_s}s")
    start = time.perf_counter()

    # initialize success counters keyed by camera name (or index)
    if cam_names is not None:
        success_counts = {name: 0 for name in cam_names}
    else:
        success_counts = {i: 0 for i in range(len(cam_list))}

    while time.perf_counter() - start < duration_s:
        for i, c in enumerate(cam_list):
            name = cam_names[i] if cam_names is not None else i
            try:
                # prefer non-blocking async read if available
                if hasattr(c, "async_read"):
                    try:
                        c.async_read(timeout_ms=500)
                    except Exception:
                        # async_read failed (timeout or error), just continue to next iteration
                        # DO NOT fallback to .read() as it might conflict with the background thread
                        # especially for RealSense cameras which enforce single-accessor to the pipeline.
                        continue
                    else:
                        # async_read succeeded; count as success
                        success_counts[name] += 1
                else:
                    frame = c.read()
                    if frame is not None:
                        success_counts[name] += 1
            except Exception as e:
                # log per-camera warmup error for later debugging
                logging.debug(f"Camera warmup read error for camera {name}: {e}")
                continue
        time.sleep(0.02)

    # Report results: which cameras had zero successful reads
    failed = [n for n, cnt in success_counts.items() if cnt == 0]
    if failed:
        logging.warning(
            "Camera warmup: some cameras had no successful reads during warmup: %s. Success counts: %s",
            failed,
            success_counts,
        )
    else:
        logging.info(f"Camera warmup successful. Success counts: {success_counts}")


if __name__ == "__main__":
    main()
